version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: linkbaby-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=linkbaby
      - DB_PASSWORD=linkbaby
      - DB_NAME=linkbaby

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linkbaby-frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: linkbaby-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: linkbaby
      MYSQL_DATABASE: linkbaby
      MYSQL_USER: linkbaby
      MYSQL_PASSWORD: linkbaby
    volumes:
      - ./db-data:/var/lib/mysql